# Generated by Django 3.2.6 on 2021-08-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210817_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
